export enum COMPETENCY_OPTIONS {
    BEHAVIOURAL = "Behavioural",
    FUNCTION = "Functional",
    DOMAIN = "Domain"
};

export enum THEME_OPTIONS {
  COMMUNICATION = "Communication",
  LEADERSHIP = "Leadership",
  TEAMWORK_COLLABORATION = "Teamwork & Collaboration",
  ADAPTABILITY = "Adaptability",
  DECISION_MAKING = "Decision Making",
  CONFLICT_RESOLUTION = "Conflict Resolution"
}

export enum SUB_THEME_OPTIONS {
  WRITTEN_COMMUNICATION = "Written Communication",
  VERBAL_COMMUNICATION = "Verbal Communication",
  PRESENTATION_SKILLS = "Presentation Skills",

  STRATEGIC_VISION = "Strategic Vision",
  PEOPLE_MANAGEMENT = "People Management",
  CHANGE_LEADERSHIP = "Change Leadership",

  CROSS_FUNCTIONAL_COLLABORATION = "Cross-functional Collaboration",
  DELEGATION = "Delegation",
  TEAM_MOTIVATION = "Team Motivation",

  RESILIENCE = "Resilience",
  INNOVATION_MINDSET = "Innovation Mindset",

  CRITICAL_THINKING = "Critical Thinking",
  EVIDENCE_BASED_DECISIONS = "Evidence-based Decisions",

  MEDIATION = "Mediation",
  NEGOTIATION_SKILLS = "Negotiation Skills"
}

export const SUB_THEME_MAP: Record<THEME_OPTIONS, SUB_THEME_OPTIONS[]> = {
  [THEME_OPTIONS.COMMUNICATION]: [
    SUB_THEME_OPTIONS.WRITTEN_COMMUNICATION,
    SUB_THEME_OPTIONS.VERBAL_COMMUNICATION,
    SUB_THEME_OPTIONS.PRESENTATION_SKILLS
  ],

  [THEME_OPTIONS.LEADERSHIP]: [
    SUB_THEME_OPTIONS.STRATEGIC_VISION,
    SUB_THEME_OPTIONS.PEOPLE_MANAGEMENT,
    SUB_THEME_OPTIONS.CHANGE_LEADERSHIP
  ],

  [THEME_OPTIONS.TEAMWORK_COLLABORATION]: [
    SUB_THEME_OPTIONS.CROSS_FUNCTIONAL_COLLABORATION,
    SUB_THEME_OPTIONS.DELEGATION,
    SUB_THEME_OPTIONS.TEAM_MOTIVATION
  ],

  [THEME_OPTIONS.ADAPTABILITY]: [
    SUB_THEME_OPTIONS.RESILIENCE,
    SUB_THEME_OPTIONS.INNOVATION_MINDSET
  ],

  [THEME_OPTIONS.DECISION_MAKING]: [
    SUB_THEME_OPTIONS.CRITICAL_THINKING,
    SUB_THEME_OPTIONS.EVIDENCE_BASED_DECISIONS
  ],

  [THEME_OPTIONS.CONFLICT_RESOLUTION]: [
    SUB_THEME_OPTIONS.MEDIATION,
    SUB_THEME_OPTIONS.NEGOTIATION_SKILLS
  ]
};

export const THEME_LIST = Object.values(THEME_OPTIONS);

export const SUB_THEME_LIST = Object.values(SUB_THEME_OPTIONS);